### PR TITLE
Add binary search example code using c++

### PR DESCRIPTION
**Pull request by RehabAbotalep**

### CODE REVIEW

**Comment by alaa-yahia** [comment]
Is the debug folder needed ya Rehab?

**Comment by alaa-yahia** [comment]
Can you please try to push your changes directly to the repository on the organization to check if the writing permissions are  working properly

**Comment by RehabAbotalep** [comment]
> working properly



> Is the debug folder needed ya Rehab?

No, I was trying to push to the forked repo in my profile , but I surprised that it came here.

**Comment by alaa-yahia** [comment]
> > working properly
> 
> > Is the debug folder needed ya Rehab?
> 
> No, I was trying to push to the forked repo in my profile , but I surprised that it came here.

It was pushed to the fork one but when you make a pull request it will appear here

**Pull request closed without merging**
